In [1]:
import pandas as pd

In [6]:
#Read in PSSA Testing CSV Files
pssa_csv = "Resources/2019 PSSA School Level Data.csv"
pssa_df = pd.read_csv(pssa_csv)
pssa_df

,AUN,School Number,County,District Name,School Name,Subject,Group,Grade,Number Scored,Percent Advanced,Percent Proficient,Percent Basic,Percent Below Basic
0,112011103,7302,Adams,BERMUDIAN SPRINGS SD,BERMUDIAN SPRINGS EL SCH,English Language Arts,All Students,3,140,7.9,52.9,27.1,12.1
1,112011103,7302,Adams,BERMUDIAN SPRINGS SD,BERMUDIAN SPRINGS EL SCH,English Language Arts,All Students,4,123,24.4,37.4,27.6,10.6
2,112011103,7302,Adams,BERMUDIAN SPRINGS SD,BERMUDIAN SPRINGS EL SCH,English Language Arts,All Students,Total,263,15.6,45.6,27.4,11.4
3,112011103,7302,Adams,BERMUDIAN SPRINGS SD,BERMUDIAN SPRINGS EL SCH,English Language Arts,Historically Underperforming,3,66,4.5,40.9,31.8,22.7
4,112011103,7302,Adams,BERMUDIAN SPRINGS SD,BERMUDIAN SPRINGS EL SCH,English Language Arts,Historically Underperforming,4,68,16.2,30.9,36.8,16.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48126,112679403,4657,York,YORK SUBURBAN SD,YORK SUBURBAN MS,Math,Historically Underperforming,Total,308,6.2,17.5,32.5,43.8
48127,112679403,4657,York,YORK SUBURBAN SD,YORK SUBURBAN MS,Science,All Students,8,245,32.2,33.5,22.9,11.4
48128,112679403,4657,York,YORK SUBURBAN SD,YORK SUBURBAN MS,Science,All Students,Total,245,32.2,33.5,22.9,11.4
48129,112679403,4657,York,YORK SUBURBAN SD,YORK SUBURBAN MS,Science,Historically Underperforming,8,112,16.1,31.3,29.5,23.2
48130,112679403,4657,York,YORK SUBURBAN SD,YORK SUBURBAN MS,Science,Historically Underperforming,Total,112,16.1,31.3,29.5,23.2

In [9]:
#Read in income csv file
income_csv = "Resources/ACSST1Y2019.S1901_data_with_overlays_2021-12-05T112002.csv"
income_df = pd.read_csv(income_csv)
income_df

,id,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000","Margin of Error!!Households!!Total!!Less than $10,000","Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to $14,999","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to $24,999",...,Estimate!!Nonfamily households!!Median income (dollars),Margin of Error!!Nonfamily households!!Median income (dollars),Estimate!!Nonfamily households!!Mean income (dollars),Margin of Error!!Nonfamily households!!Mean income (dollars),Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Household income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Family income in the past 12 months,Estimate!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months,Margin of Error!!Nonfamily households!!PERCENT ALLOCATED!!Nonfamily income in the past 12 months
0,0500000US42001,"Adams County, Pennsylvania",38703,1303,2.6,0.8,3.2,1.1,9.3,2.3,...,38218,6030,48790,4981,(X),(X),(X),(X),24.7,(X)
1,0500000US42003,"Allegheny County, Pennsylvania",553858,4070,6.4,0.6,3.6,0.4,8.4,0.6,...,40156,1182,55208,2132,(X),(X),(X),(X),31.8,(X)
2,0500000US42005,"Armstrong County, Pennsylvania",29095,869,3.1,1.1,5.7,1.5,12.2,2.2,...,32290,7362,41674,4047,(X),(X),(X),(X),41.4,(X)
3,0500000US42007,"Beaver County, Pennsylvania",70745,1646,5.2,1.3,4.8,1.3,9.9,1.9,...,35330,3160,44751,2997,(X),(X),(X),(X),33.8,(X)
4,0500000US42011,"Berks County, Pennsylvania",154696,2552,5.0,0.9,3.1,0.7,7.8,1.0,...,38557,2825,49681,3440,(X),(X),(X),(X),40.9,(X)
5,0500000US42013,"Blair County, Pennsylvania",52497,1379,6.5,1.7,4.8,1.5,10.0,1.7,...,29644,1881,42377,5733,(X),(X),(X),(X),29.0,(X)
6,0500000US42017,"Bucks County, Pennsylvania",240491,2073,3.0,0.7,1.9,0.5,7.0,0.9,...,49565,3801,72632,5200,(X),(X),(X),(X),40.2,(X)
7,0500000US42019,"Butler County, Pennsylvania",77920,1627,6.2,1.5,3.3,1.1,6.9,1.2,...,37006,6588,55801,7672,(X),(X),(X),(X),29.1,(X)
8,0500000US42021,"Cambria County, Pennsylvania",56490,1468,8.0,1.6,7.1,1.6,10.8,1.5,...,24591,2809,36061,4262,(X),(X),(X),(X),26.1,(X)
9,0500000US42025,"Carbon County, Pennsylvania",27107,1430,3.6,2.1,3.4,1.9,8.0,2.4,...,36259,6417,65593,21445,(X),(X),(X),(X),50.0,(X)
10,0500000US42027,"Centre County, Pennsylvania",58963,2042,6.8,2.3,3.7,1.2,10.1,2.1,...,32748,4183,45345,5150,(X),(X),(X),(X),29.8,(X)
11,0500000US42029,"Chester County, Pennsylvania",193234,2161,3.2,0.9,2.0,0.7,4.5,0.9,...,52711,4545,72663,6199,(X),(X),(X),(X),32.9,(X)
12,0500000US42033,"Clearfield County, Pennsylvania",31990,1085,5.5,1.8,6.2,1.6,11.1,1.8,...,30154,4927,35450,2942,(X),(X),(X),(X),38.6,(X)
13,0500000US42037,"Columbia County, Pennsylvania",26219,1002,8.3,3.4,5.6,2.1,7.1,1.9,...,33668,5163,43432,5250,(X),(X),(X),(X),23.6,(X)
14,0500000US42039,"Crawford County, Pennsylvania",35387,1116,5.0,1.5,5.7,1.4,11.3,2.5,...,29161,2374,40578,6819,(X),(X),(X),(X),31.1,(X)
15,0500000US42041,"Cumberland County, Pennsylvania",101823,1756,3.2,1.1,2.8,0.9,6.2,1.3,...,41854,4859,55097,3704,(X),(X),(X),(X),33.6,(X)
16,0500000US42043,"Dauphin County, Pennsylvania",113905,2480,6.6,1.4,2.8,0.9,9.4,1.4,...,38686,3471,49315,3989,(X),(X),(X),(X),46.5,(X)
17,0500000US42045,"Delaware County, Pennsylvania",209502,2047,5.2,0.8,2.9,0.6,6.7,0.9,...,40944,2046,57529,4062,(X),(X),(X),(X),33.3,(X)
18,0500000US42049,"Erie County, Pennsylvania",110128,1696,8.1,1.5,4.7,1.1,11.8,1.4,...,31495,2036,46042,4083,(X),(X),(X),(X),30.9,(X)
19,0500000US42051,"Fayette County, Pennsylvania",54955,1449,7.6,1.5,7.5,2.0,10.9,2.1,...,31810,3135,43239,5816,(X),(X),(X),(X),26.1,(X)
20,0500000US42055,"Franklin County, Pennsylvania",60260,1627,2.9,1.2,2.8,1.2,8.2,2.3,...,37244,5383,48476,4576,(X),(X),(X),(X),30.1,(X)
21,0500000US42063,"Indiana County, Pennsylvania",30704,1696,6.1,1.4,5.6,1.8,10.8,1.9,...,30145,5659,41840,5297,(X),(X),(X),(X),30.8,(X)
22,0500000US42069,"Lackawanna County, Pennsylvania",88154,1936,5.6,1.2,5.8,1.4,11.2,1.8,...,33186,3193,44329,3201,(X),(X),(X),(X),34.6,(X)
23,0500000US42071,"Lancaster County, Pennsylvania",204701,1948,4.7,0.9,3.3,0.8,7.4,1.1,...,37976,2850,50225,4145,(X),(X),(X),(X),37.5,(X)
24,0500000US42073,"Lawrence County, Pennsylvania",37282,916,7.3,1.5,5.5,1.4,9.5,2.0,...,28003,3253,37734,4658,(X),(X),(X),(X),32.6,(X)
25,0500000US42075,"Lebanon County, Pennsylvania",53861,1156,4.0,1.4,3.5,1.2,8.9,2.1,...,33102,2436,41968,2999,(X),(X),(X),(X),53.0,(X)
26,0500000US42077,"Lehigh County, Pennsylvania",137847,2572,4.6,1.2,3.8,1.0,8.6,1.4,...,38904,2708,52776,4619,(X),(X),(X),(X),26.0,(X)
27,0500000US42079,"Luzerne County, Pennsylvania",130890,2754,7.0,1.1,5.2,1.0,9.9,1.4,...,33063,3021,42816,2088,(X),(X),(X),(X),37.8,(X)
28,0500000US42081,"Lycoming County, Pennsylvania",44842,1617,5.6,1.8,4.8,1.8,12.1,2.2,...,30451,1694,40035,4120,(X),(X),(X),(X),29.8,(X)
29,0500000US42085,"Mercer County, Pennsylvania",46427,1338,5.3,1.7,5.8,1.6,10.2,1.9,...,34023,3598,44952,7510,(X),(X),(X),(X),33.9,(X)
30,0500000US42089,"Monroe County, Pennsylvania",56274,3491,5.6,1.9,3.5,1.6,6.3,1.9,...,34695,4533,43537,5189,(X),(X),(X),(X),36.3,(X)
31,0500000US42091,"Montgomery County, Pennsylvania",321373,2596,3.0,0.5,2.0,0.4,5.5,0.6,...,51418,1912,71466,3815,(X),(X),(X),(X),28.7,(X)
32,0500000US42095,"Northampton County, Pennsylvania",114950,1810,4.1,0.9,2.4,0.6,6.4,0.9,...,42146,5161,59052,5503,(X),(X),(X),(X),30.3,(X)
33,0500000US42097,"Northumberland County, Pennsylvania",38592,1525,5.6,1.5,5.6,1.7,9.8,1.9,...,29047,1946,35209,3227,(X),(X),(X),(X),28.7,(X)
34,0500000US42101,"Philadelphia County, Pennsylvania",619505,4709,12.2,0.8,6.6,0.6,9.7,0.8,...,35626,1078,58208,3924,(X),(X),(X),(X),34.3,(X)
35,0500000US42107,"Schuylkill County, Pennsylvania",58242,1840,5.0,1.2,6.1,1.3,10.5,1.7,...,27337,4714,44737,5481,(X),(X),(X),(X),31.5,(X)
36,0500000US42111,"Somerset County, Pennsylvania",29456,1072,5.9,1.9,4.3,1.4,13.4,2.1,...,28144,4680,41012,5670,(X),(X),(X),(X),31.6,(X)
37,0500000US42125,"Washington County, Pennsylvania",86716,1702,5.1,1.2,5.5,1.3,7.0,1.2,...,35735,3165,51650,4750,(X),(X),(X),(X),40.2,(X)
38,0500000US42129,"Westmoreland County, Pennsylvania",155147,1991,7.2,1.2,3.9,0.8,9.1,1.1,...,32304,2531,44964,3223,(X),(X),(X),(X),32.1,(X)
39,0500000US42133,"York County, Pennsylvania",175441,2373,4.3,0.9,3.1,0.7,8.0,1.0,...,38143,2311,50463,3641,(X),(X),(X),(X),29.2,(X)
40,0400000US42,Pennsylvania,5119249,11502,6.0,0.2,4.1,0.2,8.6,0.2,...,36748,424,53173,835,(X),(X),(X),(X),33.5,(X)

In [10]:
#Transform Income

# Split columns to get separated county
income_split = income_df['Geographic Area Name'].str.split(",", expand=True)
income_county_df = income_df['Geographic Area Name'].str.split(" ", expand=True)

# Create a series to add to DF
income_county_df = income_county_df.loc[:, 0]
income_df["County"] = income_county_df
income_df

# Grab desired columns & rename
income_columns = income_df.loc[:, ["County", "Estimate!!Households!!Median income (dollars)"]]
renamed_income = income_columns.rename(columns={"Estimate!!Households!!Median income (dollars)": "Household Median Income ($)"})
renamed_income

            County  Household Median Income ($)
0            Adams                        67715
1        Allegheny                        64871
2        Armstrong                        57636
3           Beaver                        60672
4            Berks                        67708
5            Blair                        51004
6            Bucks                        93767
7           Butler                        72262
8          Cambria                        49076
9           Carbon                        61111
10          Centre                        60706
11         Chester                       102016
12      Clearfield                        45643
13        Columbia                        54570
14        Crawford                        49428
15      Cumberland                        75391
16         Dauphin                        60733
17        Delaware                        77339
18            Erie                        51818
19         Fayette                        48509
20        Franklin                        62484
21         Indiana                        51914
22      Lackawanna                        53826
23       Lancaster                        67376
24        Lawrence                        50547
25         Lebanon                        61204
26          Lehigh                        65667
27         Luzerne                        53972
28        Lycoming                        53881
29          Mercer                        54543
30          Monroe                        62413
31      Montgomery                        92302
32     Northampton                        74328
33  Northumberland                        47349
34    Philadelphia                        47474
35      Schuylkill                        56295
36        Somerset                        48895
37      Washington                        65431
38    Westmoreland                        59073
39            York                        69172
40    Pennsylvania                        63463

In [11]:
# Check PSSA csv file for duplicates
pssa_df.loc[pssa_df.duplicated(subset=['AUN', 'School Number', 'County', 'District Name', 'School Name','Subject', 'Group', 'Grade', 'Number Scored', 'Percent Advanced','Percent Proficient', 'Percent Basic', 'Percent Below Basic'])]

Empty DataFrame
Columns: [AUN, School Number, County, District Name, School Name, Subject, Group, Grade, Number Scored, Percent Advanced, Percent Proficient, Percent Basic, Percent Below Basic]
Index: []